# This workflow uses actions that are not certified by GitHub.
# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: ci-ghcr

on:
  # Triggers the workflow on push or pull request events but only for selected branch
  push:
    branches:
      - main
      - next
      - beta
    tags:
      - "v*"
jobs:
  # This workflow contains jobs called "docker"
  docker:
    name: Docker build and push
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    env:
      REGISTRY_USER: ${{ env.REGISTRY_USER }}
      FRAMEWORK_NAME: ${{ env.FRAMEWORK_NAME }}
      FRAMEWORK_VERSION: ${{ env.FRAMEWORK_VERSION }}
      DIR_NODE_NAME: ${{ env.DIR_NODE_NAME }}
      DIR_TEMPLATES: ${{ env.DIR_TEMPLATES }}
    # Steps
    steps:
      - name: Check if it's a semantic-release tag
        id: is_semantic_release
        run: echo ::set-output name=is_semantic_release::$(echo "${{ github.ref }}" | grep -E '^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+')

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY_USER }}/${{ env.FRAMEWORK_NAME }}${{ env.FRAMEWORK_VERSION }}
            ghcr.io/${{ env.REGISTRY_USER }}/${{ env.FRAMEWORK_NAME }}${{ env.FRAMEWORK_VERSION }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name == 'push' && (github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/next')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && (github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/next')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/next')
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DIR_TEMPLATES }}/${{ env.FRAMEWORK_NAME }}-${{ env.FRAMEWORK_VERSION }}/${{ env.DIR_NODE_NAME }}/
          file: ${{ env.DIR_TEMPLATES }}/${{ env.FRAMEWORK_NAME }}-${{ env.FRAMEWORK_VERSION }}/${{ env.DIR_NODE_NAME }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}    
            org.opencontainers.image.title=NestJS
            org.opencontainers.image.description=Access a trusted templates of ready-to-use docker images designed to speed development, deployment, and running of applications in containerized environments.
            org.opencontainers.image.vendor=Carluchese, Principal Software Engineer/Architect
